---
output:
  bookdown::html_document2: 
    theme:
      primary: "#6D1919"
    repo: https://github.com/ulyngs/oxforddown
    pandoc_args: "--lua-filter=scripts_and_filters/colour_and_highlight.lua"
documentclass: book
---

# Conclusion 

## Introduction

Ultimately, this dissertation has argued that **political actors use multimodal gastropopulist performances as an impression management strategy to construct and legitimise their public identities**. Per Bourdieu (1984, p79), food semiotics are socially ingrained from birth, making them feel natural rather than _socially_ constructed; this subtlety is compounded by its everyday role in personal life and society. As a result, food and the body are less-scrutinised yet deeply powerful communicative modes for signalling identity and belonging. Politicians are generally observed through a cynical lens, particularly regarding what they _say_. Populists not only seek to distinguish themselves from traditional ‘elite’ politicians but establish their belonging with ‘the people’. Through taking advantage of food and the body as overlooked communicative modes, political actors can _perform_ idealised versions of their politics and public identities that are observed as glimpses into their authentic, personal ‘selves’. This is why multimodal gastropopulist performances are a highly effective impression management strategy for political actors seeking to construct and legitimise their public identities. 

However, the success of such impression management depends on not only the actor’s ability to seamlessly choreograph individual modes and features, but their authorisation by observers to deliver gastropopulist performances. This dissertation has provided a multidimensional exploration of how selected actors attempt to harness these elements. This is emphatically **not** to label the actors (in)authentic; it reflects the inextricably _performative_ nature of authenticity. **Trump’s** authorisation extends to his gastropopulist identity, so his individual performances are accepted as ‘authentic’ even if they lack careful cohesion and are overwhelmingly clustered during campaign periods. He has long established his ‘low’ culture taste preferences, appearing in adverts for: Pizza Hut [1995]; McDonalds [2002]; Oreos [2009] (Haltiwanger, 2019). As such, gastropopulism is a natural and low-cost way for Trump to construct a familiar and "entertaining" political identity --- particularly if he skips the bill, as alleged by a Maimi-based Cuban restaurant he visited for a gastropopulist performance (The Guardian, 2023). 

**Farage** has spent decades establishing his gastropopulist identity, extensively using alcohol. This _bon vivant_ identity serves to conceal the effort he expends on curating his image, particularly through unflattering or humorous performances. Farage understands and respects the social role of food, not only in terms of semiotics but its _affective_ role, especially for comfort and celebration. As his gastropopulism was historically filtered through the traditional ‘elite’ media, he became an expert at designing his performances to convey _his_ intended message by paying close attention to the power of less-scrutinised communicative modes. As such, the success of his impression management is no accident. Surprisingly, Farage and AOC are the most similar gastropopulist performers in this regard. Each developed their gastropopulism for their media landscape — traditional for Farage; social for AOC. **AOC** also understands and respects the social role of food, and its position in online culture. Her ‘everyday influencer’ style of gastropopulism has been integral in constructing and legitimising her public identity. Gastropopulist politainment serves to fuse her political, celebrity, and personal roles, offering an idealised window into her ‘mundane’ daily life and ‘true’ personality. These multimodal performances are carefully designed to seem effortless and stimulate parasocial engagement. 

Conversely, **Corbyn** had spent decades as a rebellious backbench MP purposefully separating his private life from his political role. Perhaps, with his long-term low profile, he viewed the contextual shift brought about by observation (turning actions into communicative performances) as a _choice_. Yet suddenly, he had to convincingly perform authenticity for his newfound highly visible roles: leader of the opposition; celebrity; ‘personal’. Thus, his hesitant adoption of gastropopulism was an attempt to integrate these roles into his public identity. While the other actors designed their gastropopulism to be observed as effortless and a reflection of their ‘true’ selves, this strategic impression management likely felt inauthentic to Corbyn. This is reflected in his inconsistent gastropopulist performances, because he did not respect their communicative potential.

## Limitations, Contributions, and Future Research 

The main limitation of this dissertation is the missing data. This is most keenly felt for AOC, who often uses ‘disappearing’ stories and livestreams to disseminate her gastropopulist performances. Echoes found of these performances were frequently edited or spliced by the echoer, thus could not tell us about how AOC uses gastropopulism. As this project purposefully aimed toward analytical, not statistical, generalisability, missing data is not as problematic. My sample [n=163] is bigger than any previous gastropopulism study (per Figure One: García-Santamaría _n=36_; Demuru _n=80_; Starita _n=150_). Under my qualitative social semiotics research approach, I had naturally reached a point of saturation, so additional data was not necessary. Indeed, my dataset generated many interesting themes that unfortunately did not fit into this dissertation. 

This dissertation represents a significant contribution to gastropopulism literature. Each analytical chapter built from the previous to deliver a cohesive and comprehensive exploration of gastropopulism. **Chapter Four: Statistical Analysis** assessed how gastropopulist performances are constructed, providing the first quantitative test of individual-, ideological-, and regional-level explanations. This supported my individual-level performance-based account, and demonstrated the limitations of conflating gastropopulism with specific ideology or region. Thus, future empirical studies should aim toward analytic, not statistical generalisability. **Chapter Five: Individual Timelines Thematic Analysis** developed an original mixed-methods design to provide an overview of each actor’s use of gastropopulism. This is an excellent method for authors and readers to understand the data. The interactive visualisations can generate insightful patterns to be developed through inductive thematic analysis, facilitating a clear sense of how each actor tailors their gastropopulism. **Chapter Six: Nationalism and Class Deductive Thematic Analysis** extended the central themes of gastropopulism literature to consider its flexibility in constructing national and class identity. This demonstrated how gastropopulism is developed for observation, emphasising its inherently performative nature. **Chapter Seven: Performative Eating Multimodal Social Semiotics Timeline Transcription** used ELAN software to develop an original framework that dissected audiovisual data into individual communicative modes and features of gastropopulism. This layout enabled a clear view into the multimodality of gastropopulist performances, exploring the communicative power of food and the body in eating performances. 

Future gastropopulism research should centre the actor, and take care not to conflate the phenomenon with ideology. Given Garcia-Santamaria (2020, p131) and Starita (2022, p94) label Italy a “country of endemic populism”, research specifically into Italian left-wing gastropopulism could illuminate how Italy’s strong gastronomic culture is integrated into its politics. In addition, further research into performative eating could use the MMSSTT frame to examine potential patterns in how the modes and features are rhythmically integrated in such performances. My work adds to the emerging field that stresses the overlooked communicative power of food for populist actors. The four analytical chapters herein — three original designs — offer future gastropopulism studies flexible, transparent, and replicable methods that explicitly disentangle (gastro)populism from ideological and regional assumptions. 

## Final reflection: Are you what you eat? 

‘_You are what you eat_’ has been a central theme of this paper, with Diehl (2017, p1) and Bourdieu (1984, p190) asserting this process as ‘proof’ of class belonging. However, I have purposefully avoided scrutinising the actor’s bodies in terms of size/shape/weight. At first this stemmed from discomfort at judging the bodies of others in this way; upon deeper reflection having completed this dissertation, this is because gastropopulist performances cannot offer useful insights into the performer’s bodily composition. 

This reflects commercial online eating performers, who are often slim yet frequently consume vast quantities of food _on camera_, with off-camera behaviour potentially including chewing and spitting or purging (through vomiting, laxatives, or exercise) (Hai-Jew, 2022, p287). This reminds us that gastropopulist performances are _performances_ and not reality; an actor’s bodily state is a result of their daily habits, of which gastropopulist performances can only offer a parasocial illusion. However, I maintain performative eating as the most effective and (almost) foolproof impression management strategy for gastropopulists cultivating such parasocial illusions. 
