---
output:
  bookdown::html_document2: 
    theme:
      primary: "#6D1919"
    repo: https://github.com/ulyngs/oxforddown
    pandoc_args: "--lua-filter=scripts_and_filters/colour_and_highlight.lua"
documentclass: book
---

# Bibliography {-}

\@kezdugdale. (01/10/2015). ‘Don't panic @[redacted unverified account] - all is well’. Tweet on Twitter, 01/10/2015. [Online] [Accessed 07/07/2023]. Available at: https://twitter.com/kezdugdale/status/649602463327211520 

Alexander, W. (2022). Ask the OEDI: Hispanic, Latino, Latina, Latinx - Which is Best?. [Online] [Accessed 07/07/2023]. Available at: https://medschool.duke.edu/blog/ask-oedi-hispanic-latino-latina-latinx-which-best 

Auguie, B. (2022). gridExtra. R package version 2.3. https://cran.r-project.org/web/packages/gridExtra/index.html 

Bast, J.  (2021).  ‘Politicians,  Parties,  and  Government  Representatives  on  Instagram:  A  Review of  Research  Approaches,  Usage  Patterns,  and  Effects’. Review of  Communication Research, 9. 193 -24 6. https://doi.org/10.12840/ISSN.2255-4165.032

Bezemer, J., and Mavers, D. (2011) ‘Multimodal transcription as academic practice: a social semiotic perspective’, International Journal of Social Research Methodology, 14:3, 191-206,  DOI: 10.1080/13645579.2011.563616

Bourdieu, P. (1984). Distinction: a social critique of the judgement of taste. London: Routledge, Taylor & Francis Group. 

Cafolla, A. (2022). ‘What does ‘hyperpop’ mean in 2022?’. Rolling Stone UK, October/November 2022. [Online] [Accessed 07/07/2023]. Available at: https://www.rollingstone.co.uk/music/features/what-does-hyperpop-mean-in-2022-23808/

Colvin, J., and Seewer, J. (2023). ‘Trump criticizes federal response to Ohio train derailment’. AP News, 22/02/2023. [Online] [Accessed 07/07/2023]. https://apnews.com/article/politics-palestinian-territories-florida-donald-trump-ohio-a2d75b1403daa5b3b02a6f0ff1258f10

Cowan, K. (2014) ‘Multimodal transcription of video: examining interaction in Early Years classrooms’, Classroom Discourse, 5:1, 6-21, DOI: 10.1080/19463014.2013.859846 

Daily Mail, (2014). ‘That's how you do it Ed! Farage shows Labour leader how to eat a bacon buttie as he campaigns for by-election’. Daily Mail, 03/10/2014. https://www.dailymail.co.uk/news/article-2778886/That-s-Ed-Farage-shows-Labour-leader-eat-bacon-buttie-campaigns-election.html [Author’s Note: video in article stopped working during writing, see YouTube video https://www.youtube.com/watch?v=jEfQhNgd_fw]

Demuru, P. (2021) ‘Gastropopulism: a sociosemiotic analysis of politicians posing as “the everyday man” via food posts on social media’, Social Semiotics, 31:3, 507- 527, DOI: 10.1080/10350330.2021.1930800 

Desus and Mero. (2020). ‘AOC Goes Back to Bartending in the Bronx  DESUS & MERO SHOWTIME’, YouTube video, 07/02/2020. [Online] [Accessed 07/07/2023]. Available at: https://www.youtube.com/watch?v=Vrvr89Z6fEw

Diehl, P. (2017). ‘The body in populism’. in Political Populism: A Handbook. DOI: 10.5771/9783845271491-361. 

ELAN (Version 6.6) [Computer software]. (2023). Nijmegen: Max Planck Institute for Psycholinguistics, The Language Archive. Retrieved from https://archive.mpi.nl/tla/elan

English, O. (2019). ‘What is Nigel Farage’s New Brexit Party?’. Byline Times, 11/02/2019. [Online] [Accessed 07/07/2023]. Available at: https://bylinetimes.com/2019/02/11/so-who-is-mr-farages-new-boss-and-what-is-the-brexit-party/

Font, N., Graziano, P. and Tsakatika, M. (2021) ‘Varieties of Inclusionary Populism? SYRIZA, Podemos and the Five Star Movement’. Government and Opposition. Cambridge University Press, 56(1), pp. 163–183. doi: 10.1017/gov.2019.17.

Fryar, C.D., Hughes, J.P., Herrick, K.A., and Ahluwalia, N. (2018). ‘Fast food consumption among adults in the United States, 2013–2016’. NCHS Data Brief, no 322. Hyattsville, MD: National Center for Health Statistics. 

García-Santamaría, S. (2020). ‘The Italian ‘Taste’: The Far-Right and the Performance of Exclusionary Populism During the European Elections’. Tripodos, (49), 129- 149. https://doi.org/10.51698/tripodos.2020.49p129-149 

García-Santamaría, S. (2021) ‘Politicians ‘Stay Home’: Left-Wing Populism and Performances of the Intimate Self on Social Media During the COVID-19 Pandemic’, Networking Knowledge: Journal of the MeCCSA Postgraduate Network, 14(1), pp. 28–50. doi: 10.31165/nk.2021.141.638. 

Goffman, E. (1959). The presentation of self in everyday life (1st Anchor books). Anchor Books.

Hai-Jew, S. (2022). ‘Performative Eating as Edutainment on YouTube: Extracting Positive and Negative Learning’ in Practical Peer-to-Peer Teaching and Learning on the Social Web, IGI Global, pp.266-297. DOI: https://doi-org.ezproxy.lib.gla.ac.uk/10.4018/978-1-7998-6496-7.ch008 

Haltiwanger, J. (2019). 12 vintage commercials that reveal who Trump was before he became president. Business Insider, 31/05/2019. [Online] [Accessed 07/07/2023]. Available at: https://www.businessinsider.com/commercials-donald-trump-starred-in-before-he-was-president-2019-5?r=US&IR=T

Hart, C., and Winter, B. (2022). ‘Gesture and legitimation in the anti-immigration discourse of Nigel Farage’. Discourse & Society, 33(1), 34–55. https://doi.org/10.1177/09579265211048560

Hattenstone, S. (2015). ‘Jeremy Corbyn: ‘I don’t do personal’. The Guardian: G2 Interview, 17/06/2015. [Online] [Accessed 07/07/2023]. Available at: https://www.theguardian.com/politics/2015/jun/17/jeremy-corbyn-labour-leadership-dont-do-personal

He, G. (2020). ‘The Diner That Every Future President Must Visit’. Eater, 30/01/2020. [Online] [Accessed 07/07/2023]. Available at: https://www.eater.com/2020/1/30/21111882/red-arrow-diner-campaign-trail-restaurant-new-hampshire 

Hopster, J. (2021). ‘Mutual affordances: the dynamics between social media and populism’. Media, Culture & Society, 43(3), 551–560. https://doi-org.ezproxy.lib.gla.ac.uk/10.1177/0163443720957889 

Hoss, O. (n.d.). Comparing Old World Wine vs. New World Wine. [Online] [Accessed 07/07/2023]. Available at: https://winelovermagazine.com/blog/comparing-old-world-wine-vs-new-world-wine/ 

Hunger, S. and Paxton, F. (2022). ‘What's in a buzzword? A systematic review of the state of populism research in political science,’. Political Science Research and Methods. Cambridge University Press, 10(3), pp. 617–633. doi: 10.1017/psrm.2021.44.

Hvitfeldt, E. (2022). emoji: Data and Function to Work with Emojis. R package version 15.0. [Online] [Accessed 19/07/2023]. Available at: https://github.com/EmilHvitfeldt/emoji 

Jayne, M., Valentine, G., & Holloway, S.L. (2008). ‘Fluid Boundaries—British Binge Drinking and European Civility: Alcohol and the Production and Consumption of Public Space’, Space and Polity, 12:1, 81-100, DOI: 10.1080/13562570801969473

Kiger, M.E. and Varpio, L. (2020). ‘Thematic analysis of qualitative data: AMEE Guide No. 131’. Medical Teacher, 42(8), 846–854. https://doi.org/10.1080/0142159x.2020.1755030

knowyourmeme.com. (2021). Reaction Images. [Online] [Accessed 19/07/2023]. Available at: https://knowyourmeme.com/memes/reaction-images 

Kress, G. (2011). ‘Multimodal discourse analysis’, in The Routledge Handbook of Discourse Analysis. ed. James Paul Gee and Michael Handford (Abingdon: Routledge, 16 Nov 2011), Routledge Handbooks Online. 

Kress, G., and Leeuwen, T. V. (2020). Reading images: The grammar of visual design. Taylor & Francis Group. IBSN: 9781000207873

Lyngs, U. (2019). ‘Oxforddown: An Oxford University thesis template for R markdown’. In GitHub repository. https://github.com/ulyngs/oxforddown; GitHub. https://doi.org/10.5281/zenodo.3484682

Marwick, A. E., and boyd, d. (2010). ‘I tweet honestly, I tweet passionately: Twitter users, context collapse, and the imagined audience’. New Media & Society, 13(1), 114–133. https://doi.org/10.1177/1461444810365313

McDonnell, A., and Wheeler, M. (2019). ‘\@realDonaldTrump: political celebrity, authenticity, and para-social engagement on Twitter’. Celebrity Studies, 10(3), 427–431. https://doi.org/10.1080/19392397.2019.1630157

Meta. (2021). ‘Our Response to the Violence in Washington’. Meta, 06/01/2021.
https://about.fb.com/news/2021/01/responding-to-the-violence-in-washington-dc/

merriam-webster.com. (2023). Wordplay: Let’s Talk ‘Tea’. [Online] [Accessed 07/07/2023]. Available at: https://www.merriam-webster.com/wordplay/tea-slang-meaning-origin 

Mielke, B. (2016). ‘Donald Trump Gets Heckled at New Hampshire Diner: 'Enjoy Your Burger, Racist!’’, ABC News, 12/01/2016. [Online] [Accessed 07/07/2023]. Available at: https://abcnews.go.com/Politics/donald-trump-heckled-hampshire-diner-enjoy-burger-racist/story?id=36218722

Mitchell, J. (2015). ‘Sea Change in Scotland’, Parliamentary Affairs, Volume 68, Issue suppl_1, September 2015, Pages 88–100, https://doi.org/10.1093/pa/gsv029  

Moffitt, B, (2016). 'Understanding Contemporary Populism: Populism as a Political Style', The Global Rise of Populism: Performance, Political Style, and Representation (Redwood City, CA, 2016; online edn, Stanford Scholarship Online, https://doi.org/10.11126/stanford/9780804796132.003.0003. BOOK OR CHAPTER?

Murphy, N. (2016). ‘Hispanic voters increasingly influential in U.S. presidential elections, Stanford expert says’. Stanford News, 09/09/2016. [Online] [Accessed 08/08/2023]. Available at: https://news.stanford.edu/2016/09/09/hispanic-voters-increasingly-influential-presidential-elections/ 

Norris, S. (2004). Analyzing Multimodal Interaction: A Methodological Framework. 10.4324/9780203379493. 

Norris, S. (2009). ‘Tempo, Auftakt, levels of actions, and practice: Rhythm in ordinary interactions’. Journal of Applied Linguistics and Professional Practice, 6(3), 333–356. https://doi.org/10.1558/japl.v6i3.333

ocasio-cortez.house.gov. (n.d.). Our District. [Online] [Accessed 08/08/2023]. Available at: https://ocasio-cortez.house.gov/about/our-district#:~:text=New%20York's%2014th%20District%20represents,of%20the%20Bronx%20and%20Queens. 

Oprysko, C. (2019). ‘Trump once again fetes football champ with fast food’. Politico, 04/03/2019. [Online] [Accessed 19/07/2023]. Available at: https://www.politico.com/story/2019/03/04/trump-football-fast-food-1201977 

Parker, A. (2016). ‘Donald Trump’s ‘Taco Bowl’ Message: ‘I Love Hispanics’’. New York Times, 05/05/2016. [Online] [Accessed 19/07/2023]. Available at: https://archive.nytimes.com/www.nytimes.com/politics/first-draft/2016/05/05/donald-trump-taco-bowl/

Peels, R. (2019). ’Replicability and replication in the humanities’. Research Integrity and Peer Review, 4, 2. https://doi.org/10.1186/s41073-018-0060-4 

Quinn, T. (2016). ‘The British Labour Party’s leadership election of 2015’. The British Journal of Politics and International Relations, 18(4), 759–778. https://doi.org/10.1177/1369148116664268

Raabe, S. (2022). vistime: Pretty Timelines in R. R package version 1.2.3. [Online] [Accessed 19/07/2023]. Available at: https://shosaco.github.io/vistime/ 

Rasulo, M. (2020) ‘“Experience Doesn’t Pay the Bills”. Exploring the Identity-Populism Nexus in Alexandria Ocasio-Cortez’s Political Activism’. Iperstoria, 15(1), pp.119-147. 

Red Arrow Diner. (2016). Trump Tower Burger in the Making, 23/02/2016. [Online] [Accessed 07/07/2023]. Available at: https://www.redarrowdiner.com/videos/trump-tower-burger-making/

Red Arrow Diner. (2023a). Full Menu. [Online] [Accessed 07/07/2023]. Available at: https://www.redarrowdiner.com/menu/

Red Arrow Diner. (2023b). Red Arrow Diner Manchester Hosts Donald Trump in New Hampshire, 27/04/2023. [Online] [Accessed 07/07/2023]. Available at: https://www.redarrowdiner.com/famous-guests/donald-trump-in-new-hampshire-at-red-arrow-diner-manchester-after-2024-presidential-campaign-event/?utm_source=rss&utm_medium=rss&utm_campaign=donald-trump-in-new-hampshire-at-red-arrow-diner-manchester-after-2024-presidential-campaign-event 

Relman, E. (2019) ‘Alexandria Ocasio-Cortez says she is 'proud' of her past after Trump dismissed her as a 'young bartender’’. Business Insider, 05/04/2019. [Online] [Accessed 07/07/2023]. Available at: https://www.businessinsider.com/alexandria-ocasio-cortez-defends-job-after-trump-calls-her-young-bartender-2019-4?r=US&IR=T

Robertson, D. (2021). ‘How ‘Stan’ Culture Infiltrated Politics’, POLITICO Magazine, 15/08/2021.  [Online] [Accessed 07/07/2023]. Available at: https://www.politico.com/news/magazine/2021/08/15/stan-cuomosexual-yanggang-harris-khive-504436

Ross, J. (2015). ‘We Got Jeremy Corbyn To Drink Irn-Bru On His Trip To Scotland’. Buzzfeed News, 01/10/2015. [Online] [Accessed 07/07/2023]. Available at: https://www.buzzfeed.com/jamieross/jeremy-corb-irn

Ruck, J. (2014). ‘Nigel Farage shows Ed Miliband how to eat a bacon sandwich’. The Guardian, 02/10/2014. [Online] [Accessed 08/08/2023]. Available at: https://www.theguardian.com/politics/2014/oct/02/nigel-farage-shows-ed-miliband-how-to-eat-a-bacon-sandwich 

Rüdiger, S. (2021). ‘Intimate consumptions: YouTube eating shows and the performance of informality’. Internet Pragmatics. 5. DOI: https://doi.org/10.1075/ip.00070.rud 

Selwyn, J. (2014). ‘In pictures: Jeremy Selwyn’. BBC News, 23/12/2014. [Online] [Accessed 08/08/2023]. Available at: https://www.bbc.co.uk/news/av/in-pictures-30548050

Sievert, C. (2020). Plotly For R. R package version 4.10.2. [Online] [Accessed 19/07/2023]. Available at: https://plotly-r.com 

Sjoberg, D. (2021). gtsummary. R package version 1.7.2. [Online] [Accessed 19/07/2023]. Available at: https://www.danieldsjoberg.com/gtsummary/index.html

St. James, E. (2015). ‘NBC fired Donald Trump for calling Mexican immigrants “rapists”’. Vox, 29/06/2015. [Online] [Accessed 07/07/2023]. Available at: https://www.vox.com/2015/6/29/8863309/donald-trump-nbc-fired-apprentice-miss-usa

Stano, S. (2015). ‘Semiotics of Food’. In: Trifonas, P. (eds) International Handbook of Semiotics. Springer, Dordrecht. https://doi.org/10.1007/978-94-017-9404-6_30 

Starita, G. D. (2022) ‘Place Branding in the Gastro-populist Age. Navigating through Giorgia Meloni and Matteo Salvini’s Exploitation of the Symbolic Nature of Food’, Fuori Luogo. Rivista di Sociologia del Territorio, Turismo, Tecnologia, 13(3), pp. 83-98. doi: 10.6093/2723-9608/9261.

Starita, G.D. & Trillò, T. (2022) ‘“Happy Monday friends! Coffee?” Matteo Salvini, good morning selfies, and the influencer politician’, Contemporary Italian Politics, 14:3, 331-351, DOI: 10.1080/23248823.2021.2005339

Street, J. (2019). ‘What is Donald Trump? Forms of ‘Celebrity’ in Celebrity Politics’. Political Studies Review, 17(1), 3–13. https://doi.org/10.1177/1478929918772995 

Swinford, S. (2017). ‘Nigel Farage hints at return to politics after a disastrous night for UKIP’. The Telegraph, 09/06/2017. [Online] [Accessed 07/07/2023]. Available at: https://www.telegraph.co.uk/news/2017/06/09/nigel-farage-hints-return-politics-fearing-labour-led-coalition/

The Guardian. (2023). ‘Trump offers ‘food for everyone’ at restaurant – then leaves without paying’. The Guardian, 15/06/2023. [Online] [Accessed 07/07/2023]. Available at: https://www.theguardian.com/us-news/2023/jun/15/donald-trump-miami-versailles-cuban-restaurant-pay

Thomas, N. (2016). ‘Nigel Farage resigns as UKIP leader’. Financial Times, 04/07/2016. [Online] [Accessed 07/07/2023]. Available at: https://www.ft.com/content/c5903e01-719a-300a-994b-daa28cc2431e

Tindall, C. (2022). 'Populism, culture and class: articulation and performance in contemporary British populism’,Contemporary Politics, 28:2, 121-143, DOI:10.1080/13569775.2021.1953766 

Torraco, R. J. (2005). ‘Writing Integrative Literature Reviews: Guidelines and Examples’. Human Resource Development Review, 4(3), 356–367. https://doi.org/10.1177/1534484305278283

Walker, P. (2021).‘Nigel Farage quits as Reform UK leader in step back from party politics’. The Guardian, 07/03/2021. [Online] [Accessed 07/07/2023]. Available at: https://www.theguardian.com/politics/2021/mar/07/nigel-farage-quits-as-reform-uk-leader-in-step-back-from-party-politics

Wang, V. (2019). ‘Ocasio-Cortez Went Back to Bartending. Slogans Were Served’.
The New York Times, 01/06/2019. [Online] [Accessed 07/07/2023]. Available at: https://www.nytimes.com/2019/05/31/nyregion/aoc-bartender-alexandria-ocasio-cortez.html#:~:text=The%20congresswoman%2C%20who%20has%20often,pay%20for%20tipped%2Dwage%20workers.&text=Officially%2C%20Representative%20Alexandria%20Ocasio%2DCortez's,pay%20for%20tipped%2Dwage%20workers

Workers Beer Company. (2023). Glastonbury Volunteers. [Online] [Accessed 26/06/2023]. Available at: https://www.workersbeer.co.uk/about/

Xie, Y. (2023). knitr: A General-Purpose Package for Dynamic Report Generation in R. R package version 1.43, https://yihui.org/knitr/.

Zummo, M. (2020). ‘Performing Authenticity on a Digital Political Stage Politainment as Interactive Practice and (Populist?) Performance’. Iperstoria. 15. 10.13136/2281-4582/2020.i15.589




